variables:
  CRI_URL: hub.cc-asp.fraunhofer.de
  CRI_PATH: ${CRI_URL}/forest-guard

stages:
  - danger
  - test
  - analysis
  - build
  - archive
  - deploy

.default:
  image: node:20.13-alpine3.19
  interruptible: true
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline

create-npm-licenses-list:
  stage: analysis
  extends: .default
  variables:
    LICENSES_LIST: 'npm-licenses-list.csv'
    LICENSES_OVERRIDES: 'third-party-licenses/npm-licenses-overrides.txt'
    EXCLUDED_PACKAGES: ''
  before_script:
    - npm ci --include dev --cache .npm --prefer-offline
    - >
      if [ -e ${LICENSES_OVERRIDES} ]; then
        EXCLUDED_PACKAGES=$(cat ${LICENSES_OVERRIDES});
      fi
  script:
    - >
      npx license-checker
      --unknown
      --csv
      --excludePackages "${EXCLUDED_PACKAGES}"
      --onlyAllow "${NPM_LICENSE_CHECKER_WHITELIST}"
      --out "${LICENSES_LIST}"
    - >
      if [ ${EXCLUDED_PACKAGES} ]; then
        echo -e "\n\nManually overridden packages excluded from the licenses check:\n${EXCLUDED_PACKAGES}" >> ${LICENSES_LIST};
      fi
    - cat "${LICENSES_LIST}"
  artifacts:
    name: 'npm-licenses-list'
    expose_as: 'NPM Licenses List'
    expire_in: 1 hour
    paths:
      - $LICENSES_LIST

danger:
  stage: danger
  extends: .default
  script:
    - npm install -g danger
    - danger ci --failOnErrors
  allow_failure: true
  only:
    - merge_requests

include:
  - 'apps/api/.gitlab-ci.yml'
  - 'apps/entity-management-svc/.gitlab-ci.yml'
  - 'apps/frontend/.gitlab-ci.yml'
  - 'apps/process-svc/.gitlab-ci.yml'

sync-to-github:
  image:
    name: alpine/git:latest
    entrypoint: ['/bin/sh', '-c']
  stage: deploy
  script:
    - git remote add github https://${GH_TOKEN}@github.com/fraunhofer-iml/forest-guard.git || true
    - git remote set-url github https://${GH_TOKEN}@github.com/fraunhofer-iml/forest-guard.git
    - git pull github main --rebase
    - git push github main
  only:
    - main

all:deploy:
  stage: deploy
  image: alpine:latest
  variables:
    GIT_STRATEGY: none
  before_script:
    - echo "Deploying images with tag $CI_COMMIT_SHA"
    - apk add --no-cache git curl bash coreutils
    - curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
    - mv kustomize /usr/local/bin/
    - git clone https://semantic-release:${GL_TOKEN}@gitlab.cc-asp.fraunhofer.de/oe260/forest-guard/pipeline.git
    - git config --global user.email "gitlab@oe260.iml.fhg.de"
    - git config --global user.name "GitLab CI/CD"
  script:
    - cd pipeline/kustomize/api/overlays/development
    - kustomize edit set image ${CRI_PATH}/api:$CI_COMMIT_SHA
    - cd ../../../entity-management/overlays/development
    - kustomize edit set image ${CRI_PATH}/entity-management:$CI_COMMIT_SHA
    - cd ../../../frontend/overlays/development
    - kustomize edit set image ${CRI_PATH}/frontend:$CI_COMMIT_SHA
    - cd ../../../process/overlays/development
    - kustomize edit set image ${CRI_PATH}/process:$CI_COMMIT_SHA
    - git commit -am '[skip ci] manifest-image update'
    - git push origin main
  only:
    - main
