stages:
  - danger
  - test
  - analysis

danger:
  stage: danger
  image: node:20
  only:
    - merge_requests
  script:
    - npm install -g danger
    - danger ci --failOnErrors
  allow_failure: true
#include:
#  - 'apps/api/.gitlab-ci.yml'
