services:
  ############
  # DATABASE #
  ############

  postgres:
    image: postgres:16.1
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=forest_guard
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio
    restart: unless-stopped
    environment:
      # TODO-MP: these envs are deprecated https://min.io/docs/minio/linux/reference/minio-server/minio-server.html#envvar.MINIO_ACCESS_KEY
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=blockchain
    ports:
      - '9000:9000'
      - '9090:9090'
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9090"

  minio-setup:
    image: minio/mc
    depends_on:
      minio:
        condition: service_started
    entrypoint: >
      /bin/sh -c "
      echo '### MinIO setup started ...';
      mc alias set local http://minio:9000 admin blockchain;
      mc mb local/forest-guard;
      mc anonymous set download local/forest-guard;
      echo '### ... MinIO setup ended';
      exit 0
      "

  ##############
  # BLOCKCHAIN #
  ##############
  blockchain-network:
    image: container-registry.gitlab.cc-asp.fraunhofer.de/silicon-economy/base/blockchainbroker/ethereum/networks/hyperledger-besu/dev-network:1.0.0
    depends_on:
      minio-setup:
        condition: service_completed_successfully
    restart: unless-stopped
    ports:
      - '8545:8545'

  blockchain-network-setup:
    build:
      context: ./blockchain
      dockerfile: Dockerfile
      args:
        GITLAB_TOKEN: ${NFT_FOLDER_GITLAB_TOKEN}
        DEPLOYMENT_MNEMONIC: ${DEPLOYMENT_MNEMONIC}
        TOKEN_NAME: ${TOKEN_NAME}
        TOKEN_SYMBOL: ${TOKEN_SYMBOL}
    depends_on:
      blockchain-network:
        condition: service_started
    environment:
      DEV_NODE_URL: 'http://blockchain-network:8545'

  #########
  # UTILS #
  #########

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_LOGS: '-error'

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    ports:
      - '8080:8080'
    command:
      - start-dev
      - --import-realm
    networks:
      default:
    environment:
      KC_HEALTH_ENABLED: 'true'
      KC_LOG_LEVEL: ERROR
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - './keycloak/realm/ForestGuard-realm.json:/opt/keycloak/data/import/realm.json'
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/localhost/8080'
      start_period: 10s
      interval: 5s
      retries: 10

networks:
  default:
    name: forest-guard-dev
    driver: bridge

volumes:
  postgres-data:
  minio-data:
