export enum Uris {
  batches = '/batches',
  batchesUpdate = '/batches/update',
  farmers = '/farmers',
  harvests = '/harvests',
  harvestsCombined = '/harvests/combined',
  related = '/related',
  proofs = '/proofs',
  exportData = '/export',
  users = '/users',
  addUser = '/users/add',
  companies = '/companies',
  addCompany = '/companies/add',
  addHarvest = '/batches/harvest',
  document = '/docs',
}
