import { Role } from '@prisma/client';
import { BatchWithRelations } from '../batch.types';

export const mockedPrismaBatchWithRelations1: BatchWithRelations = {
  id: '1',
  euInfoSystemId: '1',
  weight: 100,
  active: true,
  recipientId: '1',
  processStepId: '1',
  processStep: {
    id: '1',
    location: 'Location1',
    date: new Date(),
    processId: '1',
    farmedLandId: '1',
    executedByEntityId: '1',
    recordedByEntityId: '1',
    process: {
      id: '1',
      name: 'Process1',
    },
    farmedLand: {
      id: '1',
      country: 'Country1',
      areaInHA: 100,
      cultivationId: '1',
      description: 'Description1',
      district: 'District1',
      farmerId: '1',
      localPlotOfLandId: '1',
      nationalPlotOfLandId: '1',
      polygonData: 'PolygonData1',
      region: 'Region1',
    },
    recordedBy: {
      id: '1',
      user: {
        id: '1',
        firstName: 'User1FirstName',
        lastName: 'User1LastName',
        email: 'user1@example.com',
        mobilePhoneNumber: '1234567890',
        role: Role.EMPLOYEE,
        entityId: '1',
        companyId: '1',
        employeeId: '1',
        addressId: '1',
        personalId: '1',
        address: {
          id: '3',
          street: 'Street3',
          city: 'City3',
          state: 'State3',
          postalCode: 'PostalCode3',
          country: 'Country3',
        },
      },
      company: {
        id: '1',
        name: 'Company1',
        entityId: '1',
        addressId: '1',
        address: {
          id: '1',
          street: 'Street1',
          city: 'City1',
          state: 'State1',
          postalCode: 'PostalCode1',
          country: 'Country1',
        },
      },
    },
    executedBy: {
      id: '2',
      user: {
        id: '2',
        firstName: 'User2FirstName',
        lastName: 'User2LastName',
        email: 'user2@example.com',
        mobilePhoneNumber: '2345678901',
        role: Role.FARMER,
        entityId: '2',
        companyId: '2',
        employeeId: '2',
        addressId: '2',
        personalId: '2',
        address: {
          id: '3',
          street: 'Street3',
          city: 'City3',
          state: 'State3',
          postalCode: 'PostalCode3',
          country: 'Country3',
        },
      },
      company: {
        id: '2',
        name: 'Company2',
        entityId: '2',
        addressId: '2',
        address: {
          id: '2',
          street: 'Street2',
          city: 'City2',
          state: 'State2',
          postalCode: 'PostalCode2',
          country: 'Country2',
        },
      },
    },
  },
  recipient: {
    id: '1',
    user: {
      id: '3',
      firstName: 'RecipientFirstName',
      lastName: 'RecipientLastName',
      email: 'recipient@example.com',
      mobilePhoneNumber: '3456789012',
      role: Role.EMPLOYEE,
      entityId: '3',
      companyId: '3',
      employeeId: '3',
      addressId: '3',
      personalId: '3',
      address: {
        id: '3',
        street: 'Street3',
        city: 'City3',
        state: 'State3',
        postalCode: 'PostalCode3',
        country: 'Country3',
      },
    },
    company: {
      id: '3',
      name: 'RecipientCompany',
      entityId: '3',
      addressId: '3',
      address: {
        id: '3',
        street: 'Street3',
        city: 'City3',
        state: 'State3',
        postalCode: 'PostalCode3',
        country: 'Country3',
      },
    },
  },
};

export const mockedPrismaBatchWithRelations2: BatchWithRelations = {
  id: '2',
  euInfoSystemId: '2',
  weight: 200,
  active: false,
  recipientId: '2',
  processStepId: '2',
  processStep: {
    id: '2',
    location: 'Location2',
    date: new Date(),
    processId: '2',
    farmedLandId: '2',
    executedByEntityId: '2',
    recordedByEntityId: '2',
    process: {
      id: '2',
      name: 'Process2',
    },
    farmedLand: {
      id: '2',
      country: 'Country2',
      areaInHA: 200,
      cultivationId: '2',
      description: 'Description2',
      district: 'District2',
      farmerId: '2',
      localPlotOfLandId: '2',
      nationalPlotOfLandId: '2',
      polygonData: 'PolygonData2',
      region: 'Region2',
    },
    recordedBy: {
      id: '2',
      company: {
        id: '2',
        name: 'Company2',
        entityId: '2',
        addressId: '2',
        address: {
          id: '2',
          street: 'Street2',
          city: 'City2',
          state: 'State2',
          postalCode: 'PostalCode2',
          country: 'Country2',
        },
      },
    },
    executedBy: {
      id: '1',
      company: {
        id: '1',
        name: 'Company1',
        entityId: '1',
        addressId: '1',
        address: {
          id: '1',
          street: 'Street1',
          city: 'City1',
          state: 'State1',
          postalCode: 'PostalCode1',
          country: 'Country1',
        },
      },
    },
  },
  recipient: {
    id: '2',
    company: {
      id: '2',
      name: 'RecipientCompany',
      entityId: '2',
      addressId: '2',
      address: {
        id: '2',
        street: 'Street2',
        city: 'City2',
        state: 'State2',
        postalCode: 'PostalCode2',
        country: 'Country2',
      },
    },
  },
};
