[[chapter-system-scope-and-context]]
:docinfo: shared
:toc: left
:toclevels: 3
:sectnums:
:copyright: Open Logistics Foundation License 1.3

= System Scope and Context

This section describes the environment and scope of the {projectName} project: Who are its users, and with which other systems does it interact.
It thereby specifies the external interfaces (domain interfaces and technical interfaces to communication partners).
The {projectName} project is a black box here.

== Business Context

Stakeholders of {projectName} need to understand which data is exchanged with the environment.
All _communication_ partners (users, IT-systems, etc.) of {projectName} are described below.
It specifies (the interfaces of) all communication partners in business/domain view.
The following table explains the domain-specific inputs and outputs or interfaces, which may include domain-specific formats or communication protocols.

[cols="1,1,1,1,1,1",options="header"]
|===
| *Interface*
| *Kind*
| *Domain Inputs*
| *Domain Outputs*
| *Protocol*
| *Data format*

| TBD
| TBD
| TBD
| TBD
| TBD
| TBD
|===

== Technical Context

In contrast to the more abstract business context, here the technical view is described, e.g. different technical channels, protocols or interfaces used to realize the communication with the objects from the business context.
Actual _instances_ of building blocks communicate in the technical context.
For details see link:07-deployment-view.adoc[chapter 7].

The following technical interfaces link {projectName} to its environment:

[cols="1,1,1,1,1",options="header"]
|===
| *Interface*
| *Inputs*
| *Outputs*
| *Protocol*
| *Data format*

| TBD
| TBD
| TBD
| TBD
| TBD
|===

