[[chapter-building-block-view]]
:docinfo: shared
:toc: left
:toclevels: 3
:sectnums:
:copyright: Open Logistics Foundation License 1.3

= Building Block View

The building block view is a static and hierarchical decomposition of the system into building blocks and their relationships.
It is a collection of black box and white box descriptions for all important components.
Building blocks may be modules, components, subsystems, classes, interfaces, packages, libraries, frameworks, layers, partitions, tiers, functions, macros, operations, data structures, etc.).

In blackbox view, only the _interface_ of the component is visible, not its internals.
However, for interface specifications including all method signatures and their descriptions we refer to the _OpenAPI_ documents.
Only other kinds of interfaces are described here.
This is a simplification of arc42 (which requires short description of interfaces), to avoid redundancy and inconsistencies, and to reduce documentation efforts.

== Overview

TBD

== Building Blocks - Level 1

In level 1, the components of {projectName} and their relationships are shown.
This is a simplification of the <<Overview>>.

TBD

There are the following components with its responsibilities:

[cols="1,1,3",options="header"]
|===
| Name
| Status
| Responsibility / Description

| TBD
| TBD
| TBD
|===

For each {projectName} component we give a brief overview as a blackbox view.
For more details see <<Building Blocks - Level 2>> for the whitebox views of the components.

== Building Blocks - Level 2

In level 2, the black boxes of level 1 become white boxes.
We look into each component in detail.

TBD

== Building Blocks - Level 3

In level 3, the blackbox components occurring on level 2 are shown, which are developed within this project (i.e. not library components or components developed in other SE projects).
In the following are class diagrams being shown to give an overview of all classes and functions.

TBD

