[[chapter-building-block-view]]
:docinfo: shared
:toc: left
:toclevels: 3
:sectnums:
:copyright: Open Logistics Foundation License 1.3

= Building Block View

The building block view is a static and hierarchical decomposition of the system into building blocks and their relationships.
It is a collection descriptions for all important components.
Building blocks may be modules, components, subsystems, classes, interfaces, packages, libraries, frameworks, layers, partitions, tiers, functions, macros, operations, data structures, etc.).

For interface specifications, including all method signatures and their descriptions, we refer to the _OpenAPI_ documents.
Only other kinds of interfaces are described here.
This is a simplification of arc42 (which requires a short description of interfaces), to avoid redundancy and inconsistencies, and to reduce documentation efforts.

== Overview

The ForestGuard project mainly consists of two parts: a frontend and a backend.
The frontend is a web interface for the user and was developed using Angular.
The backend consists of an API gateway, which is responsible for routing requests from the frontend to the corresponding service, and a number of services, which provide the business logic. All three backend applications are implemented using TypeScript and Node.js.
Additionally, the backend utilizes a database, an object storage system, and a blockchain for data storage.

image:images/05_systemarchitecture_components.svg[]

== Building Blocks - Level 1

TBD

== Building Blocks - Level 2

TBD

== Building Blocks - Level 3

The following section presents the class diagram for ForestGuard, providing a comprehensive overview of all classes and their functions.

image:images/05_fg_entity_uml.svg[]
