generate:coverage:
  stage: test
  image: node:20
  script:
    - npm install
    - npx nx test api --code-coverage
  artifacts:
    paths:
      - coverage/
    expire_in: 1 week
  only:
    - merge_requests
    - main

sonarqube-check:
  dependencies:
    - generate:coverage
  stage: analysis
  image:
    name: sonarsource/sonar-scanner-cli:5.0
    entrypoint: ['']
  variables:
    SONAR_USER_HOME: '/apps/api/.sonar' # Defines the location of the analysis task cache
    GIT_DEPTH: '0' # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: '${CI_JOB_NAME}'
    paths:
      - /apps/api/.sonar/cache
  script:
    - >
      sonar-scanner
      -Dsonar.projectBaseDir=./apps/api/
      -Dsonar.pullrequest.key=${CI_COMMIT_SHA}
      -Dsonar.pullrequest.branch=${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}
      -Dsonar.pullrequest.base=main
  allow_failure: true
  only:
    - merge_requests
    - main
